CREATE DATABASE EntitySplitting
GO

USE EntitySplitting
GO

CREATE TABLE [dbo].[TM_USER](
	[USR_GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_TM_USER_USR_GUID]  DEFAULT (newsequentialid()),
	[USR_ID] [int] IDENTITY(1,1) NOT NULL,
	[USR_USER_NAME] [nvarchar](50) NOT NULL,
	[USR_USER_KEY] [nvarchar](50) NOT NULL CONSTRAINT [DF_TM_USER_USR_USER_KEY]  DEFAULT ((-1)),
	[USR_DELETED] [nvarchar](1) NOT NULL CONSTRAINT [DF_TM_USER_USR_DELETED]  DEFAULT (N'N'),
 CONSTRAINT [PK_TM_USER] PRIMARY KEY CLUSTERED 
(
	[USR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TM_USER_DETAIL](
	[UDT_GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_TM_USER_DETAIL_UDT_GUID]  DEFAULT (newsequentialid()),
	[UDT_USR_ID] [int] NOT NULL,
	[UDT_FORENAME] [nvarchar](50) NULL,
	[UDT_SURNAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_TM_USER_DETAIL] PRIMARY KEY CLUSTERED 
(
	[UDT_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TM_USER_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_TM_USER_DETAIL_TM_USER] FOREIGN KEY([UDT_USR_ID])
REFERENCES [dbo].[TM_USER] ([USR_ID])
GO

ALTER TABLE [dbo].[TM_USER_DETAIL] CHECK CONSTRAINT [FK_TM_USER_DETAIL_TM_USER]
GO

CREATE TABLE [dbo].[TM_MEMBERSHIP_USERS](
	[USR_ID] [uniqueidentifier] NOT NULL,
	[USR_ISAPPROVED] [bit] NULL,
 CONSTRAINT [PK_TM_MEMBERSHIP_USERS] PRIMARY KEY CLUSTERED 
(
	[USR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET IDENTITY_INSERT TM_USER ON

INSERT INTO [dbo].[TM_USER] ([USR_ID],[USR_GUID],[USR_USER_NAME],[USR_USER_KEY],[USR_DELETED])
VALUES (1,'51063393-7e50-4a9d-b5d1-c18151d8c07d','foo','46ff7ec3-5c46-427c-a78b-3dd4c1816c03','N')
GO

INSERT INTO [dbo].[TM_USER_DETAIL] ([UDT_GUID],[UDT_USR_ID],[UDT_FORENAME],[UDT_SURNAME])
VALUES    ('c7ec8d23-3606-4a87-9c27-562cd0ac2693',1 ,'Foo','Bar')
GO

INSERT INTO [dbo].[TM_MEMBERSHIP_USERS] ([USR_ID],[USR_ISAPPROVED])
VALUES ('46ff7ec3-5c46-427c-a78b-3dd4c1816c03',1)
GO









